---
# Tareas de verificación previa.
- name: "Pre-flight | Comprobar conectividad con Artifactory"
  ansible.builtin.uri:
    url: "https://{{ artifactory_host }}"
    method: HEAD
    validate_certs: false
  register: artifactory_check
  until: artifactory_check.status == 200
  retries: 3
  delay: 5
  ignore_errors: true

- name: "Pre-flight | Fallar si no se puede conectar a Artifactory"
  ansible.builtin.fail:
    msg: "Conexión fallida con Artifactory en https://{{ artifactory_host }} después de 3 intentos."
  when: artifactory_check.status != 200

- name: "Pre-flight | Verificar si SnapCenter ya está instalado"
  ansible.builtin.stat:
    path: "{{ snapcenter_install_marker }}"
  register: snapcenter_marker
